cleanup

diff --git a/.github/workflows/test-integration-flask.yml b/.github/workflows/test-integration-flask.yml
--- a/.github/workflows/test-integration-flask.yml
+++ b/.github/workflows/test-integration-flask.yml
@@ -108,8 +108,8 @@ jobs:
       - name: Check for failures
         if: contains(needs.test.result, 'failure')
         run: |
-          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
+          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
       - name: Check for 2.7 failures
         if: contains(needs.test-py27.result, 'failure')
         run: |
-          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
+          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
diff --git a/.github/workflows/test-integration-grpc.yml b/.github/workflows/test-integration-grpc.yml
--- a/.github/workflows/test-integration-grpc.yml
+++ b/.github/workflows/test-integration-grpc.yml
@@ -80,4 +80,4 @@ jobs:
       - name: Check for failures
         if: contains(needs.test.result, 'failure')
         run: |
-          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
+          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
